name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        env:
          AZP_URL: ${{ secrets.AZP_URL }}
          AZP_TOKEN: ${{ secrets.AZP_TOKEN }}
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          ./startup.ps1
