{
  "name": "Manual Workflow",
  "on": {
    "workflow_dispatch": {
      "inputs": {
        "runnerIds" : {
          "description": "List of comma separated integer ids for the runners.",
          "required": true,
          "default": "1, 2"
        }
      }
    }
  },
  "jobs": {
    "build": {
      "strategy": {
        "matrix": {
          "runnerId": "${{ fromJson('[' + inputs.runnerIds + ']') }}"
        }
      },
      "runs-on": "windows-latest",
      "steps": [
        {
          "name": "Checkout repository",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Run PowerShell script",
          "env": {
            "AZP_URL": "${{ secrets.AZP_URL }}",
            "AZP_TOKEN": "${{ secrets.AZP_TOKEN }}",
            "AZP_POOL": "RunnerPool"
          },
          "run": "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass\n./startup.ps1\n"
        }
      ]
    }
  }
}
