{
  "name": "RunnerDispatch",
  "run-name": "Agents for ${{ inputs.buildNumber }} by @${{ github.actor }}",
  "on": {
    "workflow_dispatch": {
      "inputs": {
        "runnerIds" : {
          "description": "List of comma separated integer ids for the runners.",
          "required": true,
          "default": "1, 2"
        },
        "buildNumber" : {
          "description": "The requesting pipeline build number.",
          "required": true,
          "default": "unknown"
        }
      }
    }
  },
  "jobs": {
    "build": {
      "strategy": {
        "matrix": {
          "runnerId": "${{ fromJSON(format('[{0}]', inputs.runnerIds)) }}"
        }
      },
      "runs-on": "windows-latest",
      "steps": [
        {
          "name": "Checkout repository",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Run PowerShell script",
          "env": {
            "AZP_URL": "${{ secrets.AZP_URL }}",
            "AZP_TOKEN": "${{ secrets.AZP_TOKEN }}",
            "AZP_POOL": "RunnerPool",
            "AZP_WORK": "C:/azdev/agent",
          },
          "run": "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass\n./startup.ps1\n"
        }
      ]
    }
  }
}
